print ('This program does math.')
a= int(input('Number 1: '))
b= int(input('Number 2: '))
print( )
print((a),('+'),(b),('='),(a)+(b))
print((a),('-'),(b),('='),(a)-(b))
print((a),('*'),(b),('='),(a*b))
print((a),('/'),(b),('='), format((a)/(b), '.2f'))
print((a),('//'),(b),('='),(a)//(b))
print((a),('^'),(b),('='),(a)**(b))
