print('This program calculates an average grade.')
a=int(input('Grade 1: '))
b=int(input('Grade 2: '))
c=int(input('Grade 3: '))
print( )
print('Grades to average:')
print(a,b,c)
print('Result:')
d=(a+b+c)
print(format((d/3),'.1f'))
